# Generated by Django 4.2.3 on 2023-07-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
