# Generated by Django 4.2.3 on 2023-07-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_gender_remove_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='DP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dp', to='user.profile'),
        ),
    ]
