# Generated by Django 4.2.3 on 2023-07-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_profile_folower'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='fav',
            field=models.ManyToManyField(related_name='favp', to=settings.AUTH_USER_MODEL),
        ),
    ]
