# Generated by Django 4.2.3 on 2023-07-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_posts_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='fav',
        ),
    ]
