# Generated by Django 4.2.3 on 2023-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='favp',
            field=models.IntegerField(default=0),
        ),
    ]
