# Generated by Django 4.2.3 on 2023-07-23 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='favp',
        ),
        migrations.AddField(
            model_name='posts',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
