# Generated by Django 4.2.3 on 2023-07-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_favposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favposts',
        ),
    ]
