# Generated by Django 4.2.3 on 2023-07-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_favposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='favorites',
        ),
    ]
