# Generated by Django 4.2.3 on 2023-07-31 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_posts_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='DP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dp', to='user.profile'),
        ),
    ]
